query getSlidesDocument($relativePath: String!) {
  getSlidesDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...SlidesParts
    }
  }
}

query getSlidesList {
  getSlidesList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...SlidesParts
        }
      }
    }
  }
}
