//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
import { gql } from 'tinacms';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
  form: Scalars['JSON'];
  values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
};

export type Query = {
  __typename?: 'Query';
  getCollection: Collection;
  getCollections: Array<Collection>;
  node: Node;
  getDocument: DocumentNode;
  getDocumentList: DocumentConnection;
  getDocumentFields: Scalars['JSON'];
  getSlidesDocument: SlidesDocument;
  getSlidesList: SlidesConnection;
};


export type QueryGetCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryGetDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetDocumentListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
};


export type QueryGetSlidesDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetSlidesListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
};

export type DocumentNode = SlidesDocument;

export type Slides = {
  __typename?: 'Slides';
  body?: Maybe<Scalars['JSON']>;
};

export type SlidesDocument = Node & Document & {
  __typename?: 'SlidesDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Slides;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type SlidesConnectionEdges = {
  __typename?: 'SlidesConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<SlidesDocument>;
};

export type SlidesConnection = Connection & {
  __typename?: 'SlidesConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<SlidesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  createDocument: DocumentNode;
  updateSlidesDocument: SlidesDocument;
  createSlidesDocument: SlidesDocument;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateSlidesDocumentArgs = {
  relativePath: Scalars['String'];
  params: SlidesMutation;
};


export type MutationCreateSlidesDocumentArgs = {
  relativePath: Scalars['String'];
  params: SlidesMutation;
};

export type DocumentMutation = {
  slides?: InputMaybe<SlidesMutation>;
};

export type SlidesMutation = {
  body?: InputMaybe<Scalars['JSON']>;
};

export type SlidesPartsFragment = { __typename?: 'Slides', body?: any | null };

export type GetSlidesDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetSlidesDocumentQuery = { __typename?: 'Query', getSlidesDocument: { __typename?: 'SlidesDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Slides', body?: any | null } } };

export type GetSlidesListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetSlidesListQuery = { __typename?: 'Query', getSlidesList: { __typename?: 'SlidesConnection', totalCount: number, edges?: Array<{ __typename?: 'SlidesConnectionEdges', node?: { __typename?: 'SlidesDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Slides', body?: any | null } } | null } | null> | null } };

export const SlidesPartsFragmentDoc = gql`
    fragment SlidesParts on Slides {
  body
}
    `;
export const GetSlidesDocumentDocument = gql`
    query getSlidesDocument($relativePath: String!) {
  getSlidesDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...SlidesParts
    }
  }
}
    ${SlidesPartsFragmentDoc}`;
export const GetSlidesListDocument = gql`
    query getSlidesList {
  getSlidesList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...SlidesParts
        }
      }
    }
  }
}
    ${SlidesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      getSlidesDocument(variables: GetSlidesDocumentQueryVariables, options?: C): Promise<{data: GetSlidesDocumentQuery, variables: GetSlidesDocumentQueryVariables, query: string}> {
        return requester<{data: GetSlidesDocumentQuery, variables: GetSlidesDocumentQueryVariables, query: string}, GetSlidesDocumentQueryVariables>(GetSlidesDocumentDocument, variables, options);
      },
    getSlidesList(variables?: GetSlidesListQueryVariables, options?: C): Promise<{data: GetSlidesListQuery, variables: GetSlidesListQueryVariables, query: string}> {
        return requester<{data: GetSlidesListQuery, variables: GetSlidesListQueryVariables, query: string}, GetSlidesListQueryVariables>(GetSlidesListDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { staticRequest } from 'tinacms'
const requester: (doc: any, vars?: any, options?: any) => Promise<any> = async (
  doc,
  vars,
  _options
) => {
  let data = {}
  try {
    data = await staticRequest({
      query: doc,
      variables: vars,
    })
  } catch (e) {
    // swallow errors related to document creation
    console.warn('Warning: There was an error when fetching data')
    console.warn(e)
  }

  return { data, query: doc, variables: vars || {} }
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = ()=>getSdk(requester)

